version: '3'

services:
  layer-one-dev:    # Clear name for Unraid interface
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: layer-one-dev
    ports:
      - "3003:3003"
    volumes:
      - ../src:/app/src
      - /app/node_modules
      - /app/.next
      - ./config/dev:/app/config
      - ./data/dev:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3003
    restart: unless-stopped    # Important for Unraid
    labels:
      - "com.unraid.container.name=Layer One Dev"
      - "com.unraid.container.icon=https://raw.githubusercontent.com/nextjs/next.js/canary/docs/public/favicon.ico"