version: '3'

services:
  layer-one-prod:    # Clear name for Unraid interface
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    container_name: layer-one-prod
    ports:
      - "3002:3002"
    volumes:
      - ./config/prod:/app/config
      - ./data/prod:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3002
    restart: unless-stopped    # Important for Unraid
    labels:
      - "com.unraid.container.name=Layer One Production"
      - "com.unraid.container.icon=https://raw.githubusercontent.com/nextjs/next.js/canary/docs/public/favicon.ico"